# Generated by Django 4.2.3 on 2025-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='preferred_dates',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
