# Generated by Django 4.2.3 on 2025-10-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_delete_at_remove_cartitem_delete_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='booking_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='special_requests',
        ),
    ]
