# Generated by Django 4.2.3 on 2025-10-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_orderitem_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('abandoned', 'Abandoned')], default='open', max_length=24),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('waiting_for_confirmation', 'Waiting for Confirmation'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=24),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=24),
        ),
    ]
