# Generated by Django 4.2.3 on 2025-10-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_remove_comment_comment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='delete_at',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
