# Generated by Django 4.2.3 on 2025-10-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_delete_at_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, help_text='Stripe session ID for payment tracking', max_length=200, null=True),
        ),
    ]
