# Generated by Django 4.2.3 on 2025-10-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_orderitem_booking_date_and_more'),
        ('bookings', '0003_payment_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orderdetail'),
        ),
    ]
