# Generated by Django 4.2.3 on 2025-10-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_guest_email_remove_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingService',
        ),
    ]
